configuration__main:
  configurations:
  - key: '0-core-version'
    value: ''
  - key: 'gw-flist'
    value: 'https://hub.gig.tech/gig-official-apps/zero-os-gw-master.flist'
  - key: 'ovs-flist'
    value: 'https://hub.gig.tech/gig-official-apps/ovs.flist'
  - key: '0-disk-flist'
    value: 'https://hub.gig.tech/gig-official-apps/0-disk-master.flist'
  - key: '0-statscollector-flist'
    value: 'https://hub.gig.tech/gig-official-apps/0-statscollector-master.flist'
  - key: 'jwt-token'
    value: ''
  - key: 'jwt-key'
    value: 'MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv'
  - key: '0-stor-organization'
    value: ''
  - key: '0-stor-namespace'
    value: ''
  - key: '0-stor-clientid'
    value: ''
  - key: '0-stor-clientsecret'
    value: ''
